[build]
  functions = "netlify/functions/bundled"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions.checkForApprovals]
  schedule = "@daily"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "node-fetch", "puppeteer", "puppeteer-core"]