[build]
  functions = "netlify/functions/bundled"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions.checkForApprovals]
  schedule = "@daily"

[functions]
  node_bundler = "esbuild"
  timeout = 30
  external_node_modules = ["@sparticuz/chromium"]